### ISSUE TITLE
XTF display of tables too cluttered by style names

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/VMCP-upconversion#19]
@LucasHorseshoeBend via email:

> What I was trying to prevent was the display shown in the second and third columns of the top table
> http://vmcp.conaltuohy.com/xtf/view?docId=tei/Uneven tabs file sample— edited/63-05-16-final TABLE EDIT.xml 
> 
> What appears is 
> 1
> bis
> 10
> u.
> 35
> 
> rather than 
> 
> 1 bis 10 u. 35 
> 
> Here is a case where the display can really inhibit or facilitate  getting the meaning of the text.

**Comment by Conal-Tuohy** [comment]
Perhaps alter the way style names are displayed inside tables?

1. perhaps don't show them at all, or
2. show them above the text, rather than in the left margin

**Comment by LucasHorseshoeBend** [comment]
If it is possible, not display style names in Print view might be best
Otherwise style names above the text
They are too valuable a diagnostic to lose altogether

**Comment by Conal-Tuohy** [comment]
With the style names on the left, tables with lots of columns were unreadable. But with style names always above a paragraph, the web page was stretched out vertically to an extent that appeared excessive (in my view). 

So I left the style names in the margin for regular paragraphs; but for paragraphs within table cells, I've changed the style names to appear above the paragraph. I've changed the colour of the style names from black to a dark grey, to reduce the potential for confusing them with the text.

Is this OK?

**Comment by LucasHorseshoeBend** [comment]
Much improved, not just in the tables as the grey style lables are much less distracting.

It remains now to distinguish between tables we have created for display purposes and the **real** tables that were in the source documents.
that is between cases where we have imposed a table such as
http://vmcp.conaltuohy.com/xtf/view?docId=tei/1850-9/1855/55-05-30-final.xml
 and those that had real tables, all of which I think are likely to have had borders in  Word source documents, like
http://vmcp.conaltuohy.com/xtf/view?docId=tei/1850-9/1859/59-01-19-final.xml

A conceptually simple solution would be to suppress cell borders in the former case, and draw them where you detect borders, as distinct from underlines, in a table. The first case above has an underline below the second last entry, 200, in the right column in the Word file (we still have to display underlines). There is a potential complication though, where the author has added underlines to distinguish sections of a table. So in the second example above, in the Word source file there are 5 horizontal lines crossing the 3rd, 4th and 5th colums at various points.

Is this as simple technically as conceptually? I have no idea!!

**Comment by Conal-Tuohy** [comment]
Great! 

Incidentally, I understand the distinction you're making between "real" and "imposed" tables, though I tend to think of both classes of tables as "real" tables myself, and the difference being a matter of how the table is formatted (i.e. a "superficial" question of the graphic design). With my TEI hat on I would consider the "essence" of a table is in its use of a grid to organise a set of values into logical categories. In that sense, the "imposed" table is just as real. 

I'm closing this issue since I believe issue #12 covers the remaining task of capturing the table borders etc. We can continue the discussion about table formatting in that other issue.
