### ISSUE TITLE
Invalid table

### ISSUE THREAD

**Issue by Conal-Tuohy** [Conal-Tuohy/VMCP-upconversion#30]
`1870-9/1872/72-09-26-final.xml` is invalid, with a couple of empty `<row/>` elements. Why?

**Comment by Conal-Tuohy** [comment]
lines 120 and 121

**Comment by LucasHorseshoeBend** [comment]
Whatever you did, the invalidity has disappeared.

**Comment by Conal-Tuohy** [comment]
Perhaps related to the issue about row-spanning cells? Anyway ... "disappeared" is good enough for me; if it comes back I'll worry about it then. ;-)
