### ISSUE TITLE
Can tables be made to display in footnotes?

### ISSUE THREAD

**Issue by LucasHorseshoeBend** [Conal-Tuohy/VMCP-upconversion#36]
See http://vmcp.conaltuohy.com/xtf/view?docId=tei/1890-6/1893/93-02-08-proofed.xml

To preserve the logical of the groupings made in the source text it is neccessary to use tables in the note. These do not display at all.

There have been other instances where tables were originally used in fns, purely for display purposes, but I was able to reformat them adequateley. That option is not open in this case.

**Comment by Conal-Tuohy** [comment]
I can't see where there's supposed to be a table. Can you clarify?

If I view the document in LibreOffice, there's no table. I assume that there's a table in the Word version (in footnote three? the long footnote?) that's being lost in the conversion to OpenDocument format. I don't have MSWord, but if I [preview the Word file in Dropbox](https://www.dropbox.com/home/Rod%20shared/Mueller%20letters/1890-6/1893?preview=93-02-08-proofed.doc), I can't see a table there either.

**Comment by LucasHorseshoeBend** [comment]
Yes, the several tables are in the long fn 3.
There are a series of them, where the curly brackets are.  I have made  the table margins visible and saved as a pdf so that you can see easily where they are.

[93-02-08-proofed.pdf](https://github.com/Conal-Tuohy/VMCP-upconversion/files/843881/93-02-08-proofed.pdf)

**Comment by LucasHorseshoeBend** [comment]
Sorry I accidentally hit the wrong button!

**Comment by Conal-Tuohy** [comment]
Haha! I wondered!

Thanks for that ... I understand completely now. Didn't we see this earlier, with some other tables in footnotes? But I see your point that tables are appropriate here. I wonder if a good work-around might not be to promote the footnote content to being a text in its own right, and simply include a reference to it, in the footnote?

**Comment by LucasHorseshoeBend** [comment]
We have now separated out the footnote, so I have closed this comment. If the layout is not preserved at conversion, there is not much you can do about it by tweaking.

 If we come across any more that can't be handled by changing the layout of the note, or by treating as a separate document, then I'll re-open.
