### ISSUE TITLE
Finding a set of files without a given style

### ISSUE THREAD

**Issue by LucasHorseshoeBend** [Conal-Tuohy/VMCP-upconversion#39]
We have as of today 5302 files set at _final_
They all should have something styled as _number_, but the analysis shows only 5298 with that style. 
I can't immediately see a way of finding those files; do you know of a method?

**Comment by Conal-Tuohy** [comment]
Good question! I am not sure if the current setup does provide a method to find files _without_ a style. I may have to change something in the indexer...

**Comment by LucasHorseshoeBend** [comment]
Its a bit more complicated than "no style":
These "fields" might be in the **wrong** style!  I've come across a couple when editing that have had _number_ as some other style, manually adjusted to give the correct font size and position!! It looks to me as if there are four "final" files that do not have _number_ styled as such, and (perhaps the same) four that do not have anything styled as _letter_

**Comment by LucasHorseshoeBend** [comment]
There were some where _number_ was styled _standard_  but your analytics allowed those to be picked up. So my guess is that they are coded as one of the other standard styles, styles that need not be present in all letters.

**Comment by LucasHorseshoeBend** [comment]
I have now found the 8 files that were missing _number_ or _letter_ styles: using successive combinations of facets to isolate the offending file into a set with a small number that needed to be inspected;  the biggest such set was 5 files, so became manageble. Time taken for each search depended on how lucky I was in choosing facets, but in all it took less than 30 minutes for each one.
So don't try to finesse the indexer. 

I think you can probably close this issue now.
