### ISSUE TITLE
Detecting addressee in letters in Mentions folders

### ISSUE THREAD

**Issue by LucasHorseshoeBend** [Conal-Tuohy/VMCP-upconversion#42]
For when you get funds:
Example file:
http://vmcp.conaltuohy.com/xtf/view?docId=tei/Mentions/Selected Mentions letters/M52-10-08-final.xml 
I noticed a problem with  **_mentions_** letters coming up with Mueller as the author; we fixed it by starting the _correspondent_ line with **_From_**.  The Author facet now helpfully shows up as, for example, "Charles La Trobe to Ronald Gunn".  But the Addressee facet for these files shows   "Ferdinand von Mueller".

I suspect that the algorithm needs to be tweaked to check for **_to_** in the text of the **_correspondent_** style, so that the part of it after **_to_** is identified as the Addressee. It would be a pity to lose the current identification of correspondent for these files which shows up everything after **_From_**, but if we have to, then it's a price I think worth paying to prevent Mueller being the default Addressee.

**Comment by Conal-Tuohy** [comment]
this has been done, and should've been closed a while ago

**Comment by LucasHorseshoeBend** [comment]
Conal, 
I'll respond to your other queries ASAP, but it might be tomorrow.

Best wishes
Arthur
