### ISSUE TITLE
One file not opening in XTF

### ISSUE THREAD

**Issue by LucasHorseshoeBend** [Conal-Tuohy/VMCP-upconversion#53]
When I search for a name that should be in the Honours ^&c file, the system finds the file, but then when I tyry to open it from the 'title' i get the mesage in each of the three panes 
**Document Not Found
Document tei/Apparatus files/Honours is not available. Please check that you have typed the address correctly or that the referring page does not have an error in its link.
Document ID: tei/Apparatus files/Honours**

When I first got the message on the weekend, I  resaved the file. Yesterday the file was updated, and again resaved. Same difficulty now.  Other three "apparatus files" work fine.

Not a critical problem for editing, but it will need looking at I guess for the new interface.

**Comment by LucasHorseshoeBend** [comment]
Still an issue in the XTF
Not in XProc
Not worth the effort to fix in XTF, so closed

**Comment by Conal-Tuohy** [comment]
The problem with XTF is a bug someone in it which doesn't like the `&` in a file name. As you say, not worth fixing XTF but it's worth avoiding punctuation characters in file names as a rule.
